### PR TITLE
fix: Resolve src folder creation in watch_and_serve.sh and blank search results for 'platte'

### LINKED ISSUE #61: Search bug? "platte"
Huh. When I use the AWESOME new search functionality: When I search for `platt` then a bunch of Platte stuff comes up. Awesome. But as soon as I add the last `e` character -- search is now `platte` -- the search results are suddenly blanked out?

### PR DESCRIPTION
**Pull request by zackha**
### Issues Addressed
This PR resolves two issues in the Nebraska TIF Report project:
1. **Src Folder Not Created with watch_and_serve.sh**:
   - When running `./watch_and_serve.sh`, the `static-www/www/src/` folder was not created, despite working correctly with `perl static-www/scripts/generate_www.pl`.
2. **Blank Search Results for 'platte'**:
   - Searching for "platte" in the search bar returned blank results, while "platt" showed expected results.

#### Src Folder Issue
- Updated `watch_and_serve.sh`:
  - Added `static-www/src` to the file watching scope to ensure changes in the `src` directory trigger site regeneration.
  - Added `cd $PROJECT_ROOT` to ensure `generate_www.pl` runs in the correct working directory.
  - Improved error logging to catch generation failures.
- Modified `generate_www.pl`:
  - Replaced `system` calls in the `copy_src` function with `File::Copy` for more reliable file copying and better error handling.

#### Search Issue
- Updated `layout.tt2`:
  - Modified the Lunr.js `handleSearch` function to combine exact and wildcard searches (`query + ' ' + query + '*'`), ensuring better matching for terms like "platte".
  - Optionally removed the Lunr.js stemmer to prioritize exact matches (if applied).
- Updated `generate_www.pl`:
  - Ensured consistent case handling in the `names` function to normalize index entries (e.g., "Platte" vs. "platte").

### Testing
- **Src Folder**:
  - Ran `./watch_and_serve.sh` and verified that `static-www/www/src/` is created with all files copied correctly.
  - Modified a file in `static-www/src/` to confirm regeneration triggers correctly.
- **Search**:
  - Tested searches for "platt" and "platte" in the browser, confirming that "platte" now returns expected results.
  - Verified `search-index.json` for consistent "Platte" entries.

### Related Files
- `watch_and_serve.sh`
- `static-www/scripts/generate_www.pl`
- `static-www/templates/layout.tt2`

### Additional Notes
- Added error logging to improve debugging in `watch_and_serve.sh`.
- Future improvements could include client-side tests for search functionality or a server-side search backend for larger datasets.

Closes #61

### CODE REVIEW

File: static-www/scripts/generate_www.pl [hunk 1]
```diff
@@ -310,11 +311,17 @@ sub fetch_chart_data {
...
+    while (my $file = readdir($dh)) {
+        next if $file =~ /^\./; # Skip . and ..
+        my $src_file = "$src_in/$file";
+        my $dst_file = "$src_out/$file";
+        if (-f $src_file) {
+            copy($src_file, $dst_file) or die "Cannot copy $src_file to $dst_file: $!";
+            say "Copied $src_file to $dst_file";
+        }
+    }
+    closedir($dh);
```
Comment (jhannah) [inline static-www/scripts/generate_www.pl:326]: Ha! Congrats! I coded Perl for 20 years, so I tried to do this "the Right Way(tm)" first, but got frustrated and punted. :)

Comment (zackha) [reply static-www/scripts/generate_www.pl:326]: 😄

**Review by jhannah — APPROVED** [review]
